import { createApiRelayProvider, type ApiRelayProvider, type ApiRelayRouting } from "@/stores/api-relay-config";
import type { StudioProviderBlueprint, StudioRouteMap } from "./types";

const CIVITAI_IMAGE = [
  "krea2-turbo",
  "krea2-raw",
  "flux1",
  "flux2-klein",
  "flux2-pro",
  "z-image-turbo",
  "civitai-grok",
  "flux2-dev",
  "sdxl",
  "anima",
  "qwen-3.0-pro",
  "seedream-4.5",
  "seedream-5.0-pro",
];
const CIVITAI_VIDEO = ["ltx2.3", "hunyuan"];

/**
 * Read a provider key from Vite env or process.env.
 * Never commit real keys. Users can also paste keys on /settings.
 */
function readEnvKey(...names: string[]): string {
  for (const name of names) {
    try {
      const vite = (import.meta as ImportMeta & { env?: Record<string, string | undefined> }).env?.[name];
      if (typeof vite === "string" && vite.trim()) return vite.trim();
    } catch {
      /* import.meta.env is unavailable in some test runners */
    }
    if (typeof process !== "undefined" && process.env) {
      const node = process.env[name];
      if (typeof node === "string" && node.trim()) return node.trim();
    }
  }
  return "";
}

const SUPERXIHE_IMAGE_KEY = readEnvKey("VITE_SUPERXIHE_IMAGE_KEY", "STUDIO_SUPERXIHE_IMAGE_KEY");
const SUPERXIHE_GROK_KEY = readEnvKey("VITE_SUPERXIHE_GROK_KEY", "STUDIO_SUPERXIHE_GROK_KEY");
const VOLCENGINE_ARK_KEY = readEnvKey("VITE_VOLCENGINE_ARK_KEY", "STUDIO_VOLCENGINE_ARK_KEY");
const CIVITAI_TOKEN = readEnvKey("VITE_CIVITAI_TOKEN", "STUDIO_CIVITAI_TOKEN");
const MODELSCOPE_TOKEN = readEnvKey("VITE_MODELSCOPE_TOKEN", "STUDIO_MODELSCOPE_TOKEN");
const HUGGINGFACE_TOKEN = readEnvKey("VITE_HUGGINGFACE_TOKEN", "STUDIO_HUGGINGFACE_TOKEN", "HF_TOKEN");
const GROK_RELAY_KEY = readEnvKey("VITE_GROK_RELAY_KEY", "STUDIO_GROK_RELAY_KEY");
const HANSYAI_KEY = readEnvKey("VITE_HANSYAI_KEY", "STUDIO_HANSYAI_KEY");

const GROK_VIDEO_PROFILES = {
  "grok-imagine-video": "xai-imagine-video" as const,
  "grok-imagine-video-1.5": "xai-imagine-video" as const,
  "grok-imagine-video-1.5-preview": "xai-imagine-video" as const,
};

const GROK_IMAGE_PROFILES = {
  "grok-imagine-image": { generate: "xai-grok-image-generate" as const, edit: "xai-grok-imagine-edit" as const },
  "grok-imagine-image-quality": { generate: "xai-grok-image-generate" as const, edit: "xai-grok-imagine-edit" as const },
  "grok-imagine-image-2.0": { generate: "xai-grok-image-generate" as const, edit: "xai-grok-imagine-edit" as const },
};

/**
 * Single wiring table. Add a provider here and it appears in 接线 / catalog / generation.
 * Keys come from env or the settings page. Templates stay so nothing was deleted.
 */
export const STUDIO_PROVIDERS: StudioProviderBlueprint[] = [
  {
    id: "preset-grok-relay",
    name: "Grok 中转",
    adapter: "xai-imagine",
    baseUrl: "https://sub2.alibb123.ccwu.cc/v1",
    apiKey: GROK_RELAY_KEY,
    enabled: Boolean(GROK_RELAY_KEY),
    capabilities: ["text", "image", "video"],
    remark: "Grok Imagine 图 / 视频 / 文本。图生图走 /images/edits，最多 3 张参考；视频走首帧+尾帧+分镜静帧。",
    models: [
      "grok-4.6",
      "grok-4.5",
      "grok-4.3",
      "grok-imagine-image-quality",
      "grok-imagine-image",
      "grok-imagine-image-2.0",
      "grok-imagine-video",
      "grok-imagine-video-1.5",
      "grok-imagine-video-1.5-preview",
    ],
    textModels: ["grok-4.6", "grok-4.5", "grok-4.3"],
    imageModels: ["grok-imagine-image-quality", "grok-imagine-image", "grok-imagine-image-2.0"],
    videoModels: ["grok-imagine-video", "grok-imagine-video-1.5", "grok-imagine-video-1.5-preview"],
    audioModels: [],
    nsfw: true,
    videoCapabilityProfiles: GROK_VIDEO_PROFILES,
    imageCapabilityProfiles: GROK_IMAGE_PROFILES,
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos/generations", videosPoll: "/videos/{id}" },
  },
  {
    id: "preset-xai-official",
    name: "xAI 官方",
    adapter: "xai-imagine",
    baseUrl: "https://api.x.ai/v1",
    apiKey: "",
    enabled: true,
    capabilities: ["text", "image", "video"],
    remark: "官方 api.x.ai。Key 由服务端注入，不进浏览器。",
    models: [
      "grok-4.6",
      "grok-4.5",
      "grok-imagine-image-quality",
      "grok-imagine-image",
      "grok-imagine-image-2.0",
      "grok-imagine-video",
      "grok-imagine-video-1.5",
    ],
    textModels: ["grok-4.6", "grok-4.5"],
    imageModels: ["grok-imagine-image-quality", "grok-imagine-image", "grok-imagine-image-2.0"],
    videoModels: ["grok-imagine-video", "grok-imagine-video-1.5"],
    audioModels: [],
    nsfw: true,
    videoCapabilityProfiles: GROK_VIDEO_PROFILES,
    imageCapabilityProfiles: GROK_IMAGE_PROFILES,
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos/generations", videosPoll: "/videos/{id}" },
  },
  {
    id: "preset-openai",
    name: "OpenAI 官方",
    adapter: "openai-compat",
    baseUrl: "https://api.openai.com/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["image", "video"],
    remark: "官方 api.openai.com。生图 gpt-image-2，视频 sora-2。填平台 Key 后启用。",
    models: ["gpt-image-2", "gpt-image-1.5", "sora-2", "sora-2-pro"],
    textModels: [],
    imageModels: ["gpt-image-2", "gpt-image-1.5"],
    videoModels: ["sora-2", "sora-2-pro"],
    audioModels: [],
    imageCapabilityProfiles: {
      "gpt-image-2": { generate: "openai-gpt-image-2-generate", edit: "openai-gpt-image-2-edit" },
      "gpt-image-1.5": { generate: "openai-gpt-image-legacy-generate", edit: "openai-gpt-image-legacy-edit" },
    },
    videoCapabilityProfiles: { "sora-2": "openai-video", "sora-2-pro": "openai-video" },
    endpoints: { images: "/images/generations", videosCreate: "/videos", videosPoll: "/videos/{id}" },
  },
  {
    id: "preset-hansyai",
    name: "Hansyai",
    adapter: "openai-compat",
    baseUrl: "https://hansyai.cn/v1",
    apiKey: HANSYAI_KEY,
    enabled: Boolean(HANSYAI_KEY),
    capabilities: ["text"],
    remark: "Hansyai GPT-5 文本。故事导演分析备用。",
    models: ["gpt-5.6", "gpt-5.5", "gpt-5.4", "gpt-5.2"],
    textModels: ["gpt-5.6", "gpt-5.5", "gpt-5.4", "gpt-5.2"],
    imageModels: [],
    videoModels: [],
    audioModels: [],
    endpoints: { chat: "/chat/completions" },
  },
  {
    id: "preset-modelscope",
    name: "ModelScope 魔搭",
    adapter: "modelscope",
    baseUrl: "https://api-inference.modelscope.ai/v1",
    apiKey: MODELSCOPE_TOKEN,
    enabled: Boolean(MODELSCOPE_TOKEN),
    capabilities: ["image"],
    remark: "国际站 API-Inference（modelscope.ai）。异步生图 /v1/images/generations，轮询 /v1/tasks。",
    models: ["Qwen/Qwen-Image", "Tongyi-MAI/Z-Image-Turbo", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509"],
    textModels: [],
    imageModels: ["Qwen/Qwen-Image", "Tongyi-MAI/Z-Image-Turbo", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509"],
    videoModels: [],
    audioModels: [],
    endpoints: { images: "/images/generations" },
  },
  {
    id: "preset-huggingface",
    name: "Hugging Face",
    adapter: "huggingface",
    baseUrl: "https://router.huggingface.co/nscale/v1",
    apiKey: HUGGINGFACE_TOKEN,
    enabled: Boolean(HUGGINGFACE_TOKEN),
    capabilities: ["image"],
    remark: "HF Inference Providers。生图走 nscale /v1/images/generations，返回 b64_json。FLUX.2-dev 走编辑。",
    models: ["black-forest-labs/FLUX.1-schnell", "black-forest-labs/FLUX.2-dev", "Tongyi-MAI/Z-Image-Turbo"],
    textModels: [],
    imageModels: ["black-forest-labs/FLUX.1-schnell", "black-forest-labs/FLUX.2-dev", "Tongyi-MAI/Z-Image-Turbo"],
    videoModels: [],
    audioModels: [],
    endpoints: { images: "/images/generations", models: "/models" },
  },
  {
    id: "preset-superxihe-image",
    name: "SuperXihe 生图",
    adapter: "openai-compat",
    baseUrl: "https://superxihe.com/v1",
    apiKey: SUPERXIHE_IMAGE_KEY,
    enabled: Boolean(SUPERXIHE_IMAGE_KEY),
    capabilities: ["image"],
    remark: "OpenAI 兼容 Images API：/images/generations",
    models: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1"],
    textModels: [],
    imageModels: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1"],
    videoModels: [],
    audioModels: [],
    endpoints: { images: "/images/generations" },
  },
  {
    id: "preset-superxihe-grok",
    name: "SuperXihe Grok",
    adapter: "xai-imagine",
    baseUrl: "https://superxihe.com/v1",
    apiKey: SUPERXIHE_GROK_KEY,
    enabled: Boolean(SUPERXIHE_GROK_KEY),
    capabilities: ["text", "image", "video"],
    remark: "Grok 文本 / Imagine 图视频。视频官方 /videos/generations。",
    models: [
      "grok-4.6",
      "grok-4.5",
      "grok-4.3",
      "grok-imagine-image-quality",
      "grok-imagine-image",
      "grok-imagine-video",
      "grok-imagine-video-1.5-preview",
    ],
    textModels: ["grok-4.6", "grok-4.5", "grok-4.3"],
    imageModels: ["grok-imagine-image-quality", "grok-imagine-image"],
    videoModels: ["grok-imagine-video", "grok-imagine-video-1.5-preview"],
    audioModels: [],
    nsfw: true,
    videoCapabilityProfiles: GROK_VIDEO_PROFILES,
    imageCapabilityProfiles: GROK_IMAGE_PROFILES,
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos/generations", videosPoll: "/videos/{id}" },
  },
  {
    id: "preset-volcengine-plan",
    name: "火山方舟 Agent Plan",
    adapter: "ark-plan",
    baseUrl: "https://ark.cn-beijing.volces.com/api/plan/v3",
    apiKey: VOLCENGINE_ARK_KEY,
    enabled: Boolean(VOLCENGINE_ARK_KEY),
    capabilities: ["image", "video"],
    remark: "官方 Agent Plan /api/plan/v3。生图 Seedream 5.0 Lite 已实测。视频需 Medium+。",
    models: [
      "doubao-seedream-5.0-lite",
      "doubao-seedream-5.0",
      "doubao-seedance-1.5-pro",
      "doubao-seedance-2.0",
      "doubao-seedance-2.0-fast",
      "doubao-seedance-2.0-mini",
    ],
    textModels: [],
    imageModels: ["doubao-seedream-5.0-lite", "doubao-seedream-5.0"],
    videoModels: ["doubao-seedance-1.5-pro", "doubao-seedance-2.0", "doubao-seedance-2.0-fast", "doubao-seedance-2.0-mini"],
    audioModels: [],
    endpoints: { images: "/images/generations", videosCreate: "/contents/generations/tasks", videosPoll: "/contents/generations/tasks/{id}" },
  },
  {
    id: "preset-civitai",
    name: "Civitai Orchestration",
    adapter: "civitai",
    baseUrl: "https://orchestration.civitai.com/v2/consumer",
    apiKey: CIVITAI_TOKEN,
    enabled: Boolean(CIVITAI_TOKEN),
    capabilities: ["image", "video"],
    nsfw: true,
    remark: "官方 POST /v2/consumer/workflows，$type imageGen/videoGen，allowMatureContent。",
    models: [...CIVITAI_IMAGE, ...CIVITAI_VIDEO],
    textModels: [],
    imageModels: CIVITAI_IMAGE,
    videoModels: CIVITAI_VIDEO,
    audioModels: [],
    endpoints: { images: "/workflows", videosCreate: "/workflows" },
  },
  {
    id: "preset-aliyun-dashscope",
    name: "阿里云百炼",
    adapter: "dashscope",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video"],
    remark: "通义千问 / 万相。生图兼容 /images/generations，视频走 DashScope 原生异步。",
    models: [
      "qwen-plus",
      "qwen-max",
      "qwen-image-2.0-pro",
      "qwen-image-plus",
      "wan2.6-t2i",
      "wan2.7-image",
      "wan2.6-t2v",
      "wan2.6-i2v",
      "wan2.7-t2v",
      "wan2.7-i2v",
      "happyhorse-1.1-t2v",
    ],
    textModels: ["qwen-plus", "qwen-max"],
    imageModels: ["qwen-image-2.0-pro", "qwen-image-plus", "wan2.6-t2i", "wan2.7-image"],
    videoModels: ["wan2.6-t2v", "wan2.6-i2v", "wan2.7-t2v", "wan2.7-i2v", "happyhorse-1.1-t2v"],
    audioModels: [],
    endpoints: { chat: "/chat/completions", images: "/images/generations" },
  },
  {
    id: "preset-aliyun-tokenplan",
    name: "阿里云 Token Plan",
    adapter: "dashscope",
    baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video", "audio"],
    remark: "阿里云 Token Plan 套餐端点。",
    models: ["qwen-image-2.0-pro", "wan2.7-image", "happyhorse-1.1-t2v", "qwen-audio-3.0-tts-plus"],
    textModels: [],
    imageModels: ["qwen-image-2.0-pro", "wan2.7-image"],
    videoModels: ["happyhorse-1.1-t2v"],
    audioModels: ["qwen-audio-3.0-tts-plus"],
    endpoints: { images: "/images/generations" },
  },
  {
    id: "preset-volcengine-ark",
    name: "火山方舟（标准 Ark）",
    adapter: "ark-plan",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    apiKey: "",
    enabled: false,
    capabilities: ["image", "video"],
    remark: "标准 /api/v3（非 Agent Plan）。模型 ID 带日期后缀。有 Agent Plan 请用上面那条。",
    models: ["doubao-seedream-5-0-lite-260128", "doubao-seedance-2-0-260128"],
    textModels: [],
    imageModels: ["doubao-seedream-5-0-lite-260128"],
    videoModels: ["doubao-seedance-2-0-260128"],
    audioModels: [],
    endpoints: { images: "/images/generations", videosCreate: "/contents/generations/tasks" },
  },
  {
    id: "preset-agnes-ai",
    name: "Agnes AI",
    adapter: "agnes",
    baseUrl: "https://apihub.agnes-ai.com/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video"],
    remark: "Agnes 多模态。视频 POST /videos，模型 agnes-video-v2.0。",
    models: ["agnes-2.5-flash", "agnes-image-2.1-flash", "agnes-video-v2.0"],
    textModels: ["agnes-2.5-flash", "agnes-2.5-pro-alpha"],
    imageModels: ["agnes-image-2.1-flash", "agnes-image-2.0-flash"],
    videoModels: ["agnes-video-v2.0"],
    audioModels: [],
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos" },
  },
  {
    id: "preset-sensenova",
    name: "商汤日日新",
    adapter: "sensenova",
    baseUrl: "https://token.sensenova.cn/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image"],
    remark: "无视频。生图 size 仅接受 2048x2048 等大尺寸。",
    models: ["sensenova-u1-fast", "sensenova-6.7-flash-lite"],
    textModels: ["sensenova-6.7-flash-lite"],
    imageModels: ["sensenova-u1-fast"],
    videoModels: [],
    audioModels: [],
    endpoints: { chat: "/chat/completions", images: "/images/generations" },
  },
  {
    id: "preset-fal",
    name: "Fal.ai",
    adapter: "fal",
    baseUrl: "https://fal.run",
    apiKey: "",
    enabled: false,
    capabilities: ["image", "video"],
    nsfw: true,
    remark: "Flux 2、Nano Banana、可灵、海螺、Veo。Authorization: Key。填 Fal Key 后启用。",
    models: [
      "flux-2-pro",
      "flux-2-flex",
      "flux-2-flash",
      "flux-dev",
      "flux-schnell",
      "nano-banana",
      "nano-banana-pro",
      "seedream-4.5",
      "kling-3-pro",
      "kling-3-turbo",
      "hailuo-2.3",
      "veo-3.1",
      "wan-pro",
      "minimax-h3",
    ],
    textModels: [],
    imageModels: ["flux-2-pro", "flux-2-flex", "flux-2-flash", "flux-dev", "flux-schnell", "nano-banana", "nano-banana-pro", "seedream-4.5"],
    videoModels: ["kling-3-pro", "kling-3-turbo", "hailuo-2.3", "veo-3.1", "wan-pro", "minimax-h3"],
    audioModels: [],
    endpoints: { images: "/fal-ai/flux-2-pro", videosCreate: "/fal-ai/kling-video/v3/pro/text-to-video" },
  },
  {
    id: "preset-kling",
    name: "可灵 Kling",
    adapter: "openai-compat",
    baseUrl: "https://api-singapore.klingai.com/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["video"],
    remark: "快手可灵官方国际站。填开发者 Key。国内站需改域名。",
    models: ["kling-v3", "kling-v3-omni"],
    textModels: [],
    imageModels: [],
    videoModels: ["kling-v3", "kling-v3-omni"],
    audioModels: [],
    endpoints: { videosCreate: "/videos/generations", videosPoll: "/videos/{id}" },
  },
  {
    id: "preset-minimax",
    name: "MiniMax 海螺",
    adapter: "openai-compat",
    baseUrl: "https://api.minimax.io/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["video"],
    remark: "海螺 Hailuo / H3。填 MiniMax Key。也可走上面的 Fal 聚合。",
    models: ["MiniMax-Hailuo-2.3", "MiniMax-Hailuo-02"],
    textModels: [],
    imageModels: [],
    videoModels: ["MiniMax-Hailuo-2.3", "MiniMax-Hailuo-02"],
    audioModels: [],
    endpoints: { videosCreate: "/video_generation", videosPoll: "/query/video_generation" },
  },
  {
    id: "preset-custom-compat",
    name: "自定义 OpenAI 兼容",
    adapter: "openai-compat",
    baseUrl: "https://api.example.com/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video"],
    remark: "自己的中转。按官方 Images / Chat / Videos 字段接线。",
    models: [],
    textModels: [],
    imageModels: [],
    videoModels: [],
    audioModels: [],
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos/generations" },
  },
];

export const STUDIO_ROUTES: StudioRouteMap = {
  text: { providerId: "preset-grok-relay", model: "grok-4.6" },
  image: { providerId: "preset-grok-relay", model: "grok-imagine-image" },
  video: { providerId: "preset-grok-relay", model: "grok-imagine-video" },
  audio: { providerId: "preset-aliyun-tokenplan", model: "qwen-audio-3.0-tts-plus" },
};

export function studioRelays(): ApiRelayProvider[] {
  const providers = Array.isArray(STUDIO_PROVIDERS) ? STUDIO_PROVIDERS : [];
  return providers.map((item) =>
    createApiRelayProvider({
      id: item.id,
      name: item.name,
      baseUrl: item.baseUrl,
      apiKey: item.apiKey,
      adapterType: item.adapter,
      protocol: item.adapter,
      enabled: item.enabled,
      capabilities: item.capabilities,
      remark: item.remark,
      allowMatureContent: item.nsfw === true || item.adapter === "civitai" || item.adapter === "fal",
      models: item.models,
      textModels: item.textModels,
      imageModels: item.imageModels,
      videoModels: item.videoModels,
      audioModels: item.audioModels,
      endpoints: item.endpoints,
      videoCapabilityProfiles: item.videoCapabilityProfiles,
      imageCapabilityProfiles: item.imageCapabilityProfiles,
    }),
  );
}

export function studioRouting(): ApiRelayRouting {
  return {
    text: { source: "relay", providerId: STUDIO_ROUTES.text.providerId, model: STUDIO_ROUTES.text.model },
    image: { source: "relay", providerId: STUDIO_ROUTES.image.providerId, model: STUDIO_ROUTES.image.model },
    video: { source: "relay", providerId: STUDIO_ROUTES.video.providerId, model: STUDIO_ROUTES.video.model },
    audio: { source: "relay", providerId: STUDIO_ROUTES.audio.providerId, model: STUDIO_ROUTES.audio.model },
  };
}

const MANAGED_IDS = new Set(STUDIO_PROVIDERS.map((item) => item.id).concat("legacy-default-relay"));

export function shouldReplaceManagedRelays(relays: ApiRelayProvider[] | undefined) {
  if (!Array.isArray(relays) || relays.length === 0) return true;
  return relays.every((item) => MANAGED_IDS.has(item.id));
}
