import { createApiRelayProvider, type ApiRelayProvider, type ApiRelayRouting } from "@/stores/api-relay-config";
import type { StudioProviderBlueprint, StudioRouteMap } from "./types";

const CIVITAI_IMAGE = [
  "krea2-turbo",
  "krea2-raw",
  "flux1",
  "flux2-klein",
  "flux2-pro",
  "z-image-turbo",
  "civitai-grok",
  "flux2-dev",
  "sdxl",
  "anima",
  "qwen-3.0-pro",
  "seedream-4.5",
  "seedream-5.0-pro",
];
const CIVITAI_VIDEO = ["ltx2.3", "hunyuan"];

/**
 * Shared wiring is imported by browser code. Keep provider credentials out of
 * this module; users can enter keys in settings and persist them via relay-vault.
 */
const SUPERXIHE_IMAGE_KEY = "";
const SUPERXIHE_GROK_KEY = "";
const VOLCENGINE_ARK_KEY = "";
const CIVITAI_TOKEN = "";
const MODELSCOPE_TOKEN = "";
const MODELSCOPE_CN_TOKEN = "";
const NANOGPT_KEY = "";
const HUGGINGFACE_TOKEN = "";
const GROK_RELAY_KEY = "";
const HANSYAI_KEY = "";
const AGNES_KEY = "";
const SENSENOVA_KEY = "";

const GROK_VIDEO_PROFILES = {
  "grok-imagine-video": "xai-imagine-video" as const,
  "grok-imagine-video-1.5": "xai-imagine-video" as const,
  "grok-imagine-video-1.5-preview": "xai-imagine-video" as const,
};

const GROK_IMAGE_PROFILES = {
  "grok-imagine-image": { generate: "xai-grok-image-generate" as const, edit: "xai-grok-imagine-edit" as const },
  "grok-imagine-image-quality": { generate: "xai-grok-image-generate" as const, edit: "xai-grok-imagine-edit" as const },
  "grok-imagine-image-2.0": { generate: "xai-grok-imagine-2-generate" as const, edit: "xai-grok-imagine-2-edit" as const },
};

/**
 * Single wiring table. Add a provider here and it appears in 接线 / catalog;
 * only its declared runnable capabilities enter generation.
 * Credentials are supplied by settings/relay-vault. Templates stay so nothing was deleted.
 */
export const STUDIO_PROVIDERS: StudioProviderBlueprint[] = [
  {
    id: "preset-grok-relay",
    name: "Grok 中转",
    adapter: "xai-imagine",
    baseUrl: "https://sub.alibb123.ccwu.cc/v1",
    apiKey: GROK_RELAY_KEY,
    enabled: Boolean(GROK_RELAY_KEY),
    capabilities: ["text", "image", "video"],
    remark: "Grok Imagine 图 / 视频 / 文本。图生图走 /images/edits，最多 3 张参考；视频走首帧+尾帧+分镜静帧。",
    models: [
      "grok-4.6",
      "grok-4.5",
      "grok-4.3",
      "grok-imagine-image-quality",
      "grok-imagine-image",
      "grok-imagine-image-2.0",
      "grok-imagine-video",
      "grok-imagine-video-1.5",
      "grok-imagine-video-1.5-preview",
    ],
    textModels: ["grok-4.6", "grok-4.5", "grok-4.3"],
    imageModels: ["grok-imagine-image-quality", "grok-imagine-image", "grok-imagine-image-2.0"],
    videoModels: ["grok-imagine-video", "grok-imagine-video-1.5", "grok-imagine-video-1.5-preview"],
    audioModels: [],
    nsfw: true,
    videoCapabilityProfiles: GROK_VIDEO_PROFILES,
    imageCapabilityProfiles: GROK_IMAGE_PROFILES,
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos/generations", videosPoll: "/videos/{id}" },
  },
  {
    id: "preset-xai-official",
    name: "xAI 官方",
    adapter: "xai-imagine",
    baseUrl: "https://api.x.ai/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video"],
    remark: "官方 api.x.ai。视频 I2V 只发 image.url，R2V 只发 reference_images，二者互斥；无静帧尾帧字段。",
    models: [
      "grok-4.6",
      "grok-4.5",
      "grok-imagine-image-quality",
      "grok-imagine-image",
      "grok-imagine-image-2.0",
      "grok-imagine-video",
      "grok-imagine-video-1.5",
    ],
    textModels: ["grok-4.6", "grok-4.5"],
    imageModels: ["grok-imagine-image-quality", "grok-imagine-image", "grok-imagine-image-2.0"],
    videoModels: ["grok-imagine-video", "grok-imagine-video-1.5"],
    audioModels: [],
    nsfw: true,
    videoCapabilityProfiles: GROK_VIDEO_PROFILES,
    imageCapabilityProfiles: GROK_IMAGE_PROFILES,
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos/generations", videosPoll: "/videos/{id}" },
  },
  {
    id: "preset-openai",
    name: "OpenAI 官方",
    adapter: "openai-compat",
    baseUrl: "https://api.openai.com/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["image", "video"],
    remark: "官方 api.openai.com。生图 /images/generations，改图 JSON images[]；视频 POST /videos 的 seconds/size/input_reference，完成后再 GET /videos/{id}/content。",
    models: ["gpt-image-2", "gpt-image-1.5", "sora-2", "sora-2-pro"],
    textModels: [],
    imageModels: ["gpt-image-2", "gpt-image-1.5"],
    videoModels: ["sora-2", "sora-2-pro"],
    audioModels: [],
    imageCapabilityProfiles: {
      "gpt-image-2": { generate: "openai-gpt-image-2-generate", edit: "openai-gpt-image-2-edit" },
      "gpt-image-1.5": { generate: "openai-gpt-image-legacy-generate", edit: "openai-gpt-image-legacy-edit" },
    },
    videoCapabilityProfiles: { "sora-2": "openai-video", "sora-2-pro": "openai-video" },
    endpoints: { images: "/images/generations", videosCreate: "/videos", videosPoll: "/videos/{id}" },
  },
  {
    id: "preset-hansyai",
    name: "Hansyai",
    adapter: "openai-compat",
    baseUrl: "https://hansyai.cn/v1",
    apiKey: HANSYAI_KEY,
    enabled: Boolean(HANSYAI_KEY),
    capabilities: ["text"],
    remark: "Hansyai GPT-5 文本。故事导演分析备用。",
    models: ["gpt-5.6", "gpt-5.5", "gpt-5.4", "gpt-5.2"],
    textModels: ["gpt-5.6", "gpt-5.5", "gpt-5.4", "gpt-5.2"],
    imageModels: [],
    videoModels: [],
    audioModels: [],
    endpoints: { chat: "/chat/completions" },
  },
  {
    id: "preset-modelscope",
    name: "ModelScope 魔搭（国际站）",
    adapter: "modelscope",
    baseUrl: "https://api-inference.modelscope.ai/v1",
    apiKey: MODELSCOPE_TOKEN,
    enabled: Boolean(MODELSCOPE_TOKEN),
    capabilities: ["image"],
    remark: "国际站 API-Inference（modelscope.ai）。异步生图 /v1/images/generations，轮询 /v1/tasks。国际站与中国站令牌不通用。",
    models: ["Qwen/Qwen-Image", "Tongyi-MAI/Z-Image-Turbo", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509"],
    textModels: [],
    imageModels: ["Qwen/Qwen-Image", "Tongyi-MAI/Z-Image-Turbo", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509"],
    videoModels: [],
    audioModels: [],
    endpoints: { images: "/images/generations" },
  },
  {
    id: "preset-modelscope-cn",
    name: "ModelScope 魔搭（中国站）",
    adapter: "modelscope",
    baseUrl: "https://api-inference.modelscope.cn/v1",
    apiKey: MODELSCOPE_CN_TOKEN,
    enabled: Boolean(MODELSCOPE_CN_TOKEN),
    capabilities: ["image"],
    remark: "中国站 API-Inference（modelscope.cn）。与国际站令牌不通用，需在中国站单独申请。",
    models: ["Qwen/Qwen-Image", "Tongyi-MAI/Z-Image-Turbo", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509"],
    textModels: [],
    imageModels: ["Qwen/Qwen-Image", "Tongyi-MAI/Z-Image-Turbo", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509"],
    videoModels: [],
    audioModels: [],
    endpoints: { images: "/images/generations" },
  },
  {
    id: "preset-nanogpt",
    name: "NanoGPT",
    adapter: "openai-compat",
    baseUrl: "https://nano-gpt.com/v1",
    apiKey: NANOGPT_KEY,
    enabled: Boolean(NANOGPT_KEY),
    capabilities: ["text", "image"],
    remark: "NanoGPT 聚合站。对话 /chat/completions，生图走 OpenAI 兼容 /images/generations（不是文档里的 /api/v1）。",
    models: [
      "deepseek-chat",
      "deepseek-r1",
      "kimi-k2-instruct-fast",
      "gemini-2.5-pro-preview-06-05",
      "nano-banana-2",
      "nano-banana-pro",
      "gpt-image-2",
      "gpt-image-1.5",
      "flux-2-pro",
      "flux-2-turbo",
      "seedream-v5.0-lite",
      "qwen-image-2.0-pro",
      "z-image-turbo",
      "hidream",
    ],
    textModels: ["deepseek-chat", "deepseek-r1", "kimi-k2-instruct-fast", "gemini-2.5-pro-preview-06-05"],
    imageModels: ["nano-banana-2", "nano-banana-pro", "gpt-image-2", "gpt-image-1.5", "flux-2-pro", "flux-2-turbo", "seedream-v5.0-lite", "qwen-image-2.0-pro", "z-image-turbo", "hidream"],
    videoModels: [],
    audioModels: [],
    endpoints: { chat: "/chat/completions", images: "/images/generations", models: "/models" },
  },
  {
    id: "preset-huggingface",
    name: "Hugging Face",
    adapter: "huggingface",
    baseUrl: "https://router.huggingface.co/nscale/v1",
    apiKey: HUGGINGFACE_TOKEN,
    enabled: Boolean(HUGGINGFACE_TOKEN),
    capabilities: ["image"],
    remark: "HF Inference Providers。生图走 nscale /v1/images/generations，返回 b64_json。FLUX.2-dev 走编辑。",
    models: ["black-forest-labs/FLUX.1-schnell", "black-forest-labs/FLUX.2-dev", "Tongyi-MAI/Z-Image-Turbo"],
    textModels: [],
    imageModels: ["black-forest-labs/FLUX.1-schnell", "black-forest-labs/FLUX.2-dev", "Tongyi-MAI/Z-Image-Turbo"],
    videoModels: [],
    audioModels: [],
    endpoints: { images: "/images/generations", models: "/models" },
  },
  {
    id: "preset-superxihe-image",
    name: "SuperXihe 生图",
    adapter: "openai-compat",
    baseUrl: "https://superxihe.com/v1",
    apiKey: SUPERXIHE_IMAGE_KEY,
    enabled: Boolean(SUPERXIHE_IMAGE_KEY),
    capabilities: ["image"],
    remark: "SuperXihe OpenAI 兼容。生图 /images/generations，改图 /images/edits。",
    models: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1"],
    textModels: [],
    imageModels: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1"],
    videoModels: [],
    audioModels: [],
    imageCapabilityProfiles: {
      "gpt-image-2": { generate: "openai-gpt-image-2-generate", edit: "openai-gpt-image-2-edit" },
      "gpt-image-1.5": { generate: "openai-gpt-image-legacy-generate", edit: "openai-gpt-image-legacy-edit" },
      "gpt-image-1": { generate: "openai-gpt-image-legacy-generate", edit: "openai-gpt-image-legacy-edit" },
    },
    endpoints: { images: "/images/generations" },
  },
  {
    id: "preset-superxihe-grok",
    name: "SuperXihe Grok",
    adapter: "xai-imagine",
    baseUrl: "https://superxihe.com/v1",
    apiKey: SUPERXIHE_GROK_KEY,
    enabled: Boolean(SUPERXIHE_GROK_KEY),
    capabilities: ["text", "image", "video"],
    remark: "Grok 文本 / Imagine 图视频。视频官方 /videos/generations。",
    models: [
      "grok-4.6",
      "grok-4.5",
      "grok-4.3",
      "grok-imagine-image-quality",
      "grok-imagine-image",
      "grok-imagine-video",
      "grok-imagine-video-1.5-preview",
    ],
    textModels: ["grok-4.6", "grok-4.5", "grok-4.3"],
    imageModels: ["grok-imagine-image-quality", "grok-imagine-image"],
    videoModels: ["grok-imagine-video", "grok-imagine-video-1.5-preview"],
    audioModels: [],
    nsfw: true,
    videoCapabilityProfiles: GROK_VIDEO_PROFILES,
    imageCapabilityProfiles: GROK_IMAGE_PROFILES,
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos/generations", videosPoll: "/videos/{id}" },
  },
  {
    id: "preset-volcengine-plan",
    name: "火山方舟 Agent Plan",
    adapter: "ark-plan",
    baseUrl: "https://ark.cn-beijing.volces.com/api/plan/v3",
    apiKey: VOLCENGINE_ARK_KEY,
    enabled: Boolean(VOLCENGINE_ARK_KEY),
    capabilities: ["image", "video"],
    remark: "官方 Agent Plan /api/plan/v3。生图 Seedream 5.0 Lite 已实测；当前仅暴露已配置 serializer 的 Seedance 1.5 视频。",
    models: ["doubao-seedream-5.0-lite", "doubao-seedream-5.0", "doubao-seedance-1.5-pro"],
    textModels: [],
    imageModels: ["doubao-seedream-5.0-lite", "doubao-seedream-5.0"],
    videoModels: ["doubao-seedance-1.5-pro"],
    audioModels: [],
    endpoints: { images: "/images/generations", videosCreate: "/contents/generations/tasks", videosPoll: "/contents/generations/tasks/{id}" },
  },
  {
    id: "preset-civitai",
    name: "Civitai Orchestration",
    adapter: "civitai",
    baseUrl: "https://orchestration.civitai.com/v2/consumer",
    apiKey: CIVITAI_TOKEN,
    enabled: Boolean(CIVITAI_TOKEN),
    capabilities: ["image", "video"],
    nsfw: true,
    remark: "官方 POST /v2/consumer/workflows，$type imageGen/videoGen，allowMatureContent。",
    models: [...CIVITAI_IMAGE, ...CIVITAI_VIDEO],
    textModels: [],
    imageModels: CIVITAI_IMAGE,
    videoModels: CIVITAI_VIDEO,
    audioModels: [],
    endpoints: { images: "/workflows", videosCreate: "/workflows", videosPoll: "/workflows/{id}" },
  },
  {
    id: "preset-aliyun-dashscope",
    name: "阿里云百炼",
    adapter: "dashscope",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video"],
    remark: "通义千问 / 万相。Qwen 与 Wan 2.6/2.7 生图走 DashScope 原生 multimodal-generation，不支持 compatible-mode /images/generations。视频走 video-synthesis 异步。",
    models: [
      "qwen-plus",
      "qwen-max",
      "qwen-image-2.0-pro",
      "qwen-image-plus",
      "wan2.6-t2i",
      "wan2.7-image",
      "wan3.0-video",
      "wan3.0-video-prime",
      "wan2.6-t2v",
      "wan2.6-i2v",
      "wan2.7-t2v",
      "wan2.7-i2v",
      "happyhorse-1.1-t2v",
      "happyhorse-1.1-r2v",
    ],
    textModels: ["qwen-plus", "qwen-max"],
    imageModels: ["qwen-image-2.0-pro", "qwen-image-plus", "wan2.6-t2i", "wan2.7-image"],
    videoModels: ["wan3.0-video", "wan3.0-video-prime", "wan2.6-t2v", "wan2.6-i2v", "wan2.7-t2v", "wan2.7-i2v", "happyhorse-1.1-t2v", "happyhorse-1.1-r2v"],
    audioModels: [],
    endpoints: {
      chat: "/chat/completions",
      images: "/images/generations",
      videosCreate: "/api/v1/services/aigc/video-generation/video-synthesis",
      videosPoll: "/api/v1/tasks/{id}",
    },
  },
  {
    id: "preset-aliyun-tokenplan",
    name: "阿里云 Token Plan",
    adapter: "dashscope",
    baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video", "audio"],
    remark: "官方 Token Plan 仅限 Claude Code/Codex 等交互式工具，Key 必须与 Token Plan Base URL 同方案；图像/视频/音频走 DashScope 原生端点。qwen-audio-3.0-tts-plus 使用官方 SpeechSynthesizer TTS。",
    models: [
      "qwen-image-2.0-pro",
      "qwen-image-2.0",
      "wan2.7-image",
      "wan2.7-image-pro",
      "happyhorse-1.1-t2v",
      "happyhorse-1.0-t2v",
      "happyhorse-1.1-i2v",
      "happyhorse-1.1-r2v",
      "qwen-audio-3.0-tts-plus",
    ],
    textModels: [],
    imageModels: ["qwen-image-2.0-pro", "qwen-image-2.0", "wan2.7-image-pro", "wan2.7-image"],
    videoModels: ["happyhorse-1.1-t2v", "happyhorse-1.0-t2v", "happyhorse-1.1-i2v", "happyhorse-1.1-r2v"],
    audioModels: ["qwen-audio-3.0-tts-plus"],
    endpoints: {
      chat: "/chat/completions",
      images: "/api/v1/services/aigc/multimodal-generation/generation",
      videosCreate: "/api/v1/services/aigc/video-generation/video-synthesis",
      videosPoll: "/api/v1/tasks/{id}",
      audio: "/api/v1/services/audio/tts/SpeechSynthesizer",
    },
  },
  {
    id: "preset-volcengine-ark",
    name: "火山方舟（标准 Ark）",
    adapter: "ark-plan",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    apiKey: "",
    enabled: false,
    capabilities: ["image", "video"],
    remark: "标准 /api/v3（非 Agent Plan）。模型 ID 带日期后缀。有 Agent Plan 请用上面那条。",
    models: ["doubao-seedream-5-0-lite-260128", "doubao-seedance-2-0-260128"],
    textModels: [],
    imageModels: ["doubao-seedream-5-0-lite-260128"],
    videoModels: ["doubao-seedance-2-0-260128"],
    audioModels: [],
    endpoints: { images: "/images/generations", videosCreate: "/contents/generations/tasks", videosPoll: "/contents/generations/tasks/{id}" },
  },
  {
    id: "preset-agnes-ai",
    name: "Agnes AI",
    adapter: "agnes",
    baseUrl: "https://apihub.agnes-ai.com/v1",
    apiKey: AGNES_KEY,
    enabled: Boolean(AGNES_KEY),
    capabilities: ["text", "image", "video"],
    remark: "官方 apihub。生图 2.1 Flash（1K–4K）；当前仅暴露已配置 serializer 的视频 v2.0。",
    models: [
      "agnes-2.5-pro",
      "agnes-2.5-pro-beta",
      "agnes-2.5-pro-alpha",
      "agnes-2.5-flash",
      "agnes-2.0-flash",
      "agnes-image-2.1-flash",
      "agnes-image-2.0-flash",
      "agnes-video-v2.0",
    ],
    textModels: ["agnes-2.5-pro", "agnes-2.5-pro-beta", "agnes-2.5-pro-alpha", "agnes-2.5-flash", "agnes-2.0-flash"],
    imageModels: ["agnes-image-2.1-flash", "agnes-image-2.0-flash"],
    videoModels: ["agnes-video-v2.0"],
    audioModels: [],
    imageCapabilityProfiles: {
      "agnes-image-2.1-flash": { generate: "agnes-image-2.1-generate", edit: "agnes-image-2.1-edit" },
      "agnes-image-2.0-flash": { generate: "agnes-image-2.0-generate", edit: "agnes-image-2.0-edit" },
    },
    videoCapabilityProfiles: {
      "agnes-video-v2.0": "agnes-video-v2",
    },
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos", videosPoll: "/agnesapi?video_id={id}" },
  },
  {
    id: "preset-sensenova",
    name: "商汤日日新",
    adapter: "sensenova",
    baseUrl: "https://token.sensenova.cn/v1",
    apiKey: SENSENOVA_KEY,
    enabled: Boolean(SENSENOVA_KEY),
    capabilities: ["text", "image"],
    remark: "官方 token.sensenova.cn 当前账号能拉到的全部模型。生图 U1 Fast / U1.5 Lite；文本 6.8 / 6.7 / DeepSeek V4 / GLM-5.2。无视频。",
    models: [
      "sensenova-u1-fast",
      "sensenova-u1.5-lite",
      "sensenova-6.8-flash-lite",
      "sensenova-6.7-flash-lite",
      "deepseek-v4-flash",
      "glm-5.2",
    ],
    textModels: ["sensenova-6.8-flash-lite", "sensenova-6.7-flash-lite", "deepseek-v4-flash", "glm-5.2"],
    imageModels: ["sensenova-u1-fast", "sensenova-u1.5-lite"],
    videoModels: [],
    audioModels: [],
    imageCapabilityProfiles: {
      "sensenova-u1-fast": { generate: "sensenova-u1-generate" },
      "sensenova-u1.5-lite": { generate: "sensenova-u1-generate" },
    },
    endpoints: { chat: "/chat/completions", images: "/images/generations" },
  },
  {
    id: "preset-fal",
    name: "Fal.ai",
    adapter: "fal",
    baseUrl: "https://fal.run",
    apiKey: "",
    enabled: false,
    capabilities: ["image", "video"],
    runnableCapabilities: ["image"],
    nsfw: true,
    remark: "Fal.ai 图片模型。Authorization: Key。视频模型入口保留，但当前 fal adapter 仅实现生图，视频创建/轮询尚未接线，标记为未接线。",
    models: [
      "flux-2-pro",
      "flux-2-flex",
      "flux-2-flash",
      "flux-dev",
      "flux-schnell",
      "nano-banana",
      "nano-banana-pro",
      "seedream-4.5",
      "kling-3-pro",
      "kling-3-turbo",
      "hailuo-2.3",
      "veo-3.1",
      "wan-pro",
      "minimax-h3",
    ],
    textModels: [],
    imageModels: ["flux-2-pro", "flux-2-flex", "flux-2-flash", "flux-dev", "flux-schnell", "nano-banana", "nano-banana-pro", "seedream-4.5"],
    videoModels: ["kling-3-pro", "kling-3-turbo", "hailuo-2.3", "veo-3.1", "wan-pro", "minimax-h3"],
    audioModels: [],
    endpoints: { images: "/fal-ai/flux-2-pro", videosCreate: "/fal-ai/kling-video/v3/pro/text-to-video" },
  },
  {
    id: "preset-kling",
    name: "可灵 Kling（未接线）",
    adapter: "openai-compat",
    baseUrl: "https://api-singapore.klingai.com/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["video"],
    runnableCapabilities: [],
    remark: "可灵视频模型入口保留，但当前没有专用 Kling adapter；未接线，不按 OpenAI 兼容协议发送。",
    models: ["kling-v3", "kling-v3-omni"],
    textModels: [],
    imageModels: [],
    videoModels: ["kling-v3", "kling-v3-omni"],
    audioModels: [],
    endpoints: { videosCreate: "/videos/generations", videosPoll: "/videos/{id}" },
  },
  {
    id: "preset-minimax",
    name: "MiniMax 海螺（未接线）",
    adapter: "openai-compat",
    baseUrl: "https://api.minimax.io/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["video"],
    runnableCapabilities: [],
    remark: "MiniMax 海螺视频模型入口保留，但当前没有专用 MiniMax adapter；未接线，不按 OpenAI 兼容协议发送。",
    models: ["MiniMax-Hailuo-2.3", "MiniMax-Hailuo-02"],
    textModels: [],
    imageModels: [],
    videoModels: ["MiniMax-Hailuo-2.3", "MiniMax-Hailuo-02"],
    audioModels: [],
    endpoints: { videosCreate: "/video_generation", videosPoll: "/query/video_generation" },
  },
  {
    id: "preset-custom-compat",
    name: "自定义 OpenAI 兼容",
    adapter: "openai-compat",
    baseUrl: "https://api.example.com/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video"],
    remark: "OpenAI 兼容中转。默认走兼容体，不会把猜测字段当成官方 Sora；官方 api.openai.com 才用 seconds/size/input_reference。",
    models: [],
    textModels: [],
    imageModels: [],
    videoModels: [],
    audioModels: [],
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos/generations" },
  },
];

export const STUDIO_ROUTES: StudioRouteMap = {
  text: { providerId: "preset-grok-relay", model: "grok-4.6" },
  image: { providerId: "preset-grok-relay", model: "grok-imagine-image" },
  video: { providerId: "preset-grok-relay", model: "grok-imagine-video" },
  audio: { providerId: "preset-aliyun-tokenplan", model: "qwen-audio-3.0-tts-plus" },
};

export function studioRelays(): ApiRelayProvider[] {
  try {
    const providers = Array.isArray(STUDIO_PROVIDERS) ? STUDIO_PROVIDERS : [];
    return providers.map((item) =>
      createApiRelayProvider({
        id: item.id,
        name: item.name,
        baseUrl: item.baseUrl,
        apiKey: item.apiKey,
        adapterType: item.adapter,
        protocol: item.id === "preset-openai" ? "openai-official" : item.adapter,
        authScheme: item.adapter === "fal" ? "Key" : undefined,
        enabled: item.enabled,
        capabilities: item.capabilities,
        runnableCapabilities: item.runnableCapabilities,
        remark: item.remark,
        allowMatureContent: item.nsfw === true || item.adapter === "civitai" || item.adapter === "fal",
        models: item.models || [],
        textModels: item.textModels || [],
        imageModels: item.imageModels || [],
        videoModels: item.videoModels || [],
        audioModels: item.audioModels || [],
        endpoints: item.endpoints,
        videoCapabilityProfiles: item.videoCapabilityProfiles,
        imageCapabilityProfiles: item.imageCapabilityProfiles,
      }),
    );
  } catch (err) {
    const message = `接线表加载失败：${err instanceof Error ? err.message : String(err)}`;
    if (typeof window === "undefined") return [];
    throw new Error(message);
  }
}

export function studioRouting(): ApiRelayRouting {
  return {
    text: { source: "relay", providerId: STUDIO_ROUTES.text.providerId, model: STUDIO_ROUTES.text.model },
    image: { source: "relay", providerId: STUDIO_ROUTES.image.providerId, model: STUDIO_ROUTES.image.model },
    video: { source: "relay", providerId: STUDIO_ROUTES.video.providerId, model: STUDIO_ROUTES.video.model },
    audio: { source: "relay", providerId: STUDIO_ROUTES.audio.providerId, model: STUDIO_ROUTES.audio.model },
  };
}

const MANAGED_IDS = new Set((Array.isArray(STUDIO_PROVIDERS) ? STUDIO_PROVIDERS : []).map((item) => item.id).concat("legacy-default-relay"));

export function shouldReplaceManagedRelays(relays: ApiRelayProvider[] | undefined) {
  if (!Array.isArray(relays) || relays.length === 0) return true;
  return relays.every((item) => MANAGED_IDS.has(item.id));
}
