import { createApiRelayProvider, type ApiRelayProvider, type ApiRelayRouting } from "@/stores/api-relay-config";
import { CIVITAI_ENGINES } from "./adapters/civitai";
import type { StudioProviderBlueprint, StudioRouteMap } from "./types";

const CIVITAI_IMAGE = CIVITAI_ENGINES.filter((item) => item.kind === "image").map((item) => item.id);
const CIVITAI_VIDEO = CIVITAI_ENGINES.filter((item) => item.kind === "video").map((item) => item.id);

/**
 * Single wiring table. Add a provider here and it appears in 接线 / catalog / generation.
 * Live keys (user-supplied, disposable): SuperXihe image, SuperXihe Grok, Volcengine Agent Plan, Civitai.
 * Original Boundless slots kept as disabled templates so nothing was deleted.
 */
export const STUDIO_PROVIDERS: StudioProviderBlueprint[] = [
  {
    id: "preset-superxihe-image",
    name: "SuperXihe 生图",
    adapter: "openai-compat",
    baseUrl: "https://superxihe.com/v1",
    apiKey: "sk-54340465b9c29c6810db2bf19740c3c39057c3db711b040cbd28d8a62c9ebb36",
    enabled: true,
    capabilities: ["image"],
    remark: "OpenAI 兼容 Images API：/images/generations",
    models: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1"],
    textModels: [],
    imageModels: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1"],
    videoModels: [],
    audioModels: [],
    endpoints: { images: "/images/generations" },
  },
  {
    id: "preset-superxihe-grok",
    name: "SuperXihe Grok",
    adapter: "xai-imagine",
    baseUrl: "https://superxihe.com/v1",
    apiKey: "sk-92f2462d95d3e1ae3336226b62af3d4f376aa9cb6c6279d52d1186092ecef4b9",
    enabled: true,
    capabilities: ["text", "image", "video"],
    remark: "Grok 文本 / Imagine 图视频。视频官方 /videos/generations。",
    models: [
      "grok-4.6",
      "grok-4.5",
      "grok-4.3",
      "grok-imagine-image-quality",
      "grok-imagine-image",
      "grok-imagine-video",
      "grok-imagine-video-1.5-preview",
    ],
    textModels: ["grok-4.6", "grok-4.5", "grok-4.3"],
    imageModels: ["grok-imagine-image-quality", "grok-imagine-image"],
    videoModels: ["grok-imagine-video", "grok-imagine-video-1.5-preview"],
    audioModels: [],
    nsfw: true,
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos/generations", videosPoll: "/videos/{id}" },
  },
  {
    id: "preset-volcengine-plan",
    name: "火山方舟 Agent Plan",
    adapter: "ark-plan",
    baseUrl: "https://ark.cn-beijing.volces.com/api/plan/v3",
    apiKey: "ark-8c2c51f6-b302-48fc-8f26-207f83bd8129-b50b0",
    enabled: true,
    capabilities: ["image", "video"],
    remark: "官方 Agent Plan /api/plan/v3。生图 Seedream 5.0 Lite 已实测。视频需 Medium+。",
    models: [
      "doubao-seedream-5.0-lite",
      "doubao-seedance-1.5-pro",
      "doubao-seedance-2.0",
      "doubao-seedance-2.0-fast",
      "doubao-seedance-2.0-mini",
    ],
    textModels: [],
    imageModels: ["doubao-seedream-5.0-lite"],
    videoModels: ["doubao-seedance-1.5-pro", "doubao-seedance-2.0", "doubao-seedance-2.0-fast", "doubao-seedance-2.0-mini"],
    audioModels: [],
    endpoints: { images: "/images/generations", videosCreate: "/contents/generations/tasks", videosPoll: "/contents/generations/tasks/{id}" },
  },
  {
    id: "preset-civitai",
    name: "Civitai Orchestration",
    adapter: "civitai",
    baseUrl: "https://orchestration.civitai.com/v2/consumer",
    apiKey: "29d622653173c1960a0952118df72f49",
    enabled: true,
    capabilities: ["image", "video"],
    nsfw: true,
    remark: "官方 POST /v2/consumer/workflows，$type imageGen/videoGen，allowMatureContent。",
    models: [...CIVITAI_IMAGE, ...CIVITAI_VIDEO],
    textModels: [],
    imageModels: CIVITAI_IMAGE,
    videoModels: CIVITAI_VIDEO,
    audioModels: [],
    endpoints: { images: "/workflows", videosCreate: "/workflows" },
  },
  {
    id: "preset-aliyun-dashscope",
    name: "阿里云百炼",
    adapter: "dashscope",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video"],
    remark: "通义千问 / 万相。生图兼容 /images/generations，视频走 DashScope 原生异步。",
    models: [
      "qwen-plus",
      "qwen-max",
      "qwen-image-2.0-pro",
      "qwen-image-plus",
      "wan2.6-t2i",
      "wan2.6-t2v",
      "wan2.6-i2v",
      "happyhorse-1.1-t2v",
    ],
    textModels: ["qwen-plus", "qwen-max"],
    imageModels: ["qwen-image-2.0-pro", "qwen-image-plus", "wan2.6-t2i"],
    videoModels: ["wan2.6-t2v", "wan2.6-i2v", "happyhorse-1.1-t2v"],
    audioModels: [],
    endpoints: { chat: "/chat/completions", images: "/images/generations" },
  },
  {
    id: "preset-aliyun-tokenplan",
    name: "阿里云 Token Plan",
    adapter: "dashscope",
    baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video", "audio"],
    remark: "阿里云 Token Plan 套餐端点。",
    models: ["qwen-image-2.0-pro", "wan2.7-image", "happyhorse-1.1-t2v", "qwen-audio-3.0-tts-plus"],
    textModels: [],
    imageModels: ["qwen-image-2.0-pro", "wan2.7-image"],
    videoModels: ["happyhorse-1.1-t2v"],
    audioModels: ["qwen-audio-3.0-tts-plus"],
    endpoints: { images: "/images/generations" },
  },
  {
    id: "preset-volcengine-ark",
    name: "火山方舟（标准 Ark）",
    adapter: "ark-plan",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    apiKey: "",
    enabled: false,
    capabilities: ["image", "video"],
    remark: "标准 /api/v3（非 Agent Plan）。模型 ID 带日期后缀。有 Agent Plan 请用上面那条。",
    models: ["doubao-seedream-5-0-lite-260128", "doubao-seedance-2-0-260128"],
    textModels: [],
    imageModels: ["doubao-seedream-5-0-lite-260128"],
    videoModels: ["doubao-seedance-2-0-260128"],
    audioModels: [],
    endpoints: { images: "/images/generations", videosCreate: "/contents/generations/tasks" },
  },
  {
    id: "preset-agnes-ai",
    name: "Agnes AI",
    adapter: "agnes",
    baseUrl: "https://apihub.agnes-ai.com/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video"],
    remark: "Agnes 多模态。视频 POST /videos，模型 agnes-video-v2.0。",
    models: ["agnes-2.5-flash", "agnes-image-2.1-flash", "agnes-video-v2.0"],
    textModels: ["agnes-2.5-flash", "agnes-2.5-pro-alpha"],
    imageModels: ["agnes-image-2.1-flash", "agnes-image-2.0-flash"],
    videoModels: ["agnes-video-v2.0"],
    audioModels: [],
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos" },
  },
  {
    id: "preset-sensenova",
    name: "商汤日日新",
    adapter: "sensenova",
    baseUrl: "https://token.sensenova.cn/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image"],
    remark: "无视频。生图 size 仅接受 2048x2048 等大尺寸。",
    models: ["sensenova-u1-fast", "sensenova-6.7-flash-lite"],
    textModels: ["sensenova-6.7-flash-lite"],
    imageModels: ["sensenova-u1-fast"],
    videoModels: [],
    audioModels: [],
    endpoints: { chat: "/chat/completions", images: "/images/generations" },
  },
  {
    id: "preset-fal",
    name: "Fal.ai",
    adapter: "fal",
    baseUrl: "https://fal.run",
    apiKey: "",
    enabled: false,
    capabilities: ["image"],
    nsfw: true,
    remark: "Flux 系列，Authorization: Key。成人向内容由模型自身策略决定，不含违法类别。",
    models: ["flux-dev", "flux-schnell", "flux-pro"],
    textModels: [],
    imageModels: ["flux-dev", "flux-schnell", "flux-pro"],
    videoModels: [],
    audioModels: [],
    endpoints: { images: "/fal-ai/flux/dev" },
  },
  {
    id: "preset-custom-compat",
    name: "自定义 OpenAI 兼容",
    adapter: "openai-compat",
    baseUrl: "https://api.example.com/v1",
    apiKey: "",
    enabled: false,
    capabilities: ["text", "image", "video"],
    remark: "自己的中转。按官方 Images / Chat / Videos 字段接线。",
    models: [],
    textModels: [],
    imageModels: [],
    videoModels: [],
    audioModels: [],
    endpoints: { chat: "/chat/completions", images: "/images/generations", videosCreate: "/videos/generations" },
  },
];

export const STUDIO_ROUTES: StudioRouteMap = {
  text: { providerId: "preset-superxihe-grok", model: "grok-4.6" },
  image: { providerId: "preset-volcengine-plan", model: "doubao-seedream-5.0-lite" },
  video: { providerId: "preset-superxihe-grok", model: "grok-imagine-video" },
  audio: { providerId: "preset-aliyun-tokenplan", model: "qwen-audio-3.0-tts-plus" },
};

export function studioRelays(): ApiRelayProvider[] {
  return STUDIO_PROVIDERS.map((item) =>
    createApiRelayProvider({
      id: item.id,
      name: item.name,
      baseUrl: item.baseUrl,
      apiKey: item.apiKey,
      adapterType: item.adapter,
      enabled: item.enabled,
      capabilities: item.capabilities,
      remark: item.remark,
      allowMatureContent: item.nsfw === true || item.adapter === "civitai" || item.adapter === "fal",
      models: item.models,
      textModels: item.textModels,
      imageModels: item.imageModels,
      videoModels: item.videoModels,
      audioModels: item.audioModels,
    }),
  );
}

export function studioRouting(): ApiRelayRouting {
  return {
    text: { source: "relay", providerId: STUDIO_ROUTES.text.providerId, model: STUDIO_ROUTES.text.model },
    image: { source: "relay", providerId: STUDIO_ROUTES.image.providerId, model: STUDIO_ROUTES.image.model },
    video: { source: "relay", providerId: STUDIO_ROUTES.video.providerId, model: STUDIO_ROUTES.video.model },
    audio: { source: "relay", providerId: STUDIO_ROUTES.audio.providerId, model: STUDIO_ROUTES.audio.model },
  };
}

const MANAGED_IDS = new Set(STUDIO_PROVIDERS.map((item) => item.id).concat("legacy-default-relay"));

export function shouldReplaceManagedRelays(relays: ApiRelayProvider[] | undefined) {
  if (!Array.isArray(relays) || relays.length === 0) return true;
  return relays.every((item) => MANAGED_IDS.has(item.id));
}
