import type { ApiRelayProvider } from "./api-relay-config";
import { CIVITAI_IMAGE_SERVICE_IDS, CIVITAI_VIDEO_SERVICE_IDS } from "../services/api/civitai-services.ts";

export const TOKEN_PLAN_PRESET_ID = "preset-aliyun-tokenplan";

type TokenPlanRelayShape = {
    id?: string;
    capabilities?: ApiRelayProvider["capabilities"];
    models?: string[];
    textModels?: string[];
    imageModels?: string[];
    videoModels?: string[];
    audioModels?: string[];
    imageCapabilityProfiles?: ApiRelayProvider["imageCapabilityProfiles"];
    videoCapabilityProfiles?: ApiRelayProvider["videoCapabilityProfiles"];
    audioCapabilityProfiles?: ApiRelayProvider["audioCapabilityProfiles"];
};

/**
 * Compatibility shim for callers that used to clamp Token Plan models.
 *
 * Token Plan supports separate multimodal APIs, and persisted model selections
 * are user data. Never silently replace those selections with a template list.
 */
export function clampManagedTokenPlanRelay<T extends TokenPlanRelayShape>(
    relay: T,
    _templateTextModels: readonly string[] = [],
): T {
    return relay;
}

const CIVITAI_PRESET_IMAGE_MODELS = [...CIVITAI_IMAGE_SERVICE_IDS];
const CIVITAI_PRESET_VIDEO_MODELS = [...CIVITAI_VIDEO_SERVICE_IDS];
const CIVITAI_PRESET_MODELS = [...CIVITAI_PRESET_IMAGE_MODELS, ...CIVITAI_PRESET_VIDEO_MODELS];

/**
 * 预设中转端点。
 *
 * 模型 ID 均以各家 /models 接口或官方文档实测确认为准，不要凭印象填写：
 * 错误的模型 ID 会让上游直接返回 404 model not found。
 */
export const PRESET_RELAY_ENDPOINTS: Array<Partial<ApiRelayProvider>> = [
    {
        id: "preset-superxihe-image",
        name: "SuperXihe 生图",
        baseUrl: "https://superxihe.com/v1",
        apiKey: "",
        enabled: false,
        capabilities: ["image"],
        remark: "OpenAI 兼容 gpt-image 生图",
        models: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1"],
        textModels: [],
        imageModels: ["gpt-image-2", "gpt-image-1.5", "gpt-image-1"],
        videoModels: [],
        audioModels: [],
    },
    {
        id: "preset-superxihe-grok",
        name: "SuperXihe Grok",
        baseUrl: "https://superxihe.com/v1",
        apiKey: "",
        enabled: false,
        capabilities: ["text", "image", "video"],
        remark: "Grok 文本 / Imagine 图视频。视频走官方 duration / aspect_ratio / resolution。",
        models: ["grok-4.6", "grok-4.5", "grok-4.3", "grok-imagine-image-quality", "grok-imagine-image", "grok-imagine-video", "grok-imagine-video-1.5", "grok-imagine-video-1.5-preview"],
        textModels: ["grok-4.6", "grok-4.5", "grok-4.3"],
        imageModels: ["grok-imagine-image-quality", "grok-imagine-image"],
        videoModels: ["grok-imagine-video", "grok-imagine-video-1.5", "grok-imagine-video-1.5-preview"],
        audioModels: [],
        videoCapabilityProfiles: {
            "grok-imagine-video": "xai-imagine-video",
            "grok-imagine-video-1.5": "xai-imagine-video",
            "grok-imagine-video-1.5-preview": "xai-imagine-video",
        },
    },
    {
        id: "preset-volcengine-plan",
        name: "火山方舟 Token Plan",
        baseUrl: "https://ark.cn-beijing.volces.com/api/plan/v3",
        apiKey: "",
        adapterType: "ark",
        enabled: false,
        capabilities: ["image", "video"],
        remark: "Seedream 生图 / Seedance 生视频（Token Plan /api/plan/v3）",
        models: [
            "doubao-seedream-5-0-lite-260128",
            "doubao-seedream-5-0-260128",
            "doubao-seedream-4-5-251128",
            "doubao-seedream-4-0-250828",
            "doubao-seedance-2-0-260128",
            "doubao-seedance-2-0-fast-260128",
            "doubao-seedance-2-0-mini-260615",
            "doubao-seedance-1-5-pro-251215",
        ],
        textModels: [],
        imageModels: ["doubao-seedream-5-0-lite-260128", "doubao-seedream-5-0-260128", "doubao-seedream-4-5-251128", "doubao-seedream-4-0-250828"],
        videoModels: ["doubao-seedance-2-0-260128", "doubao-seedance-2-0-fast-260128", "doubao-seedance-2-0-mini-260615", "doubao-seedance-1-5-pro-251215"],
        videoCapabilityProfiles: {
            "doubao-seedance-2-0-260128": "ark-seedance-2",
            "doubao-seedance-2-0-fast-260128": "ark-seedance-2-fast",
            "doubao-seedance-2-0-mini-260615": "ark-seedance-2-mini",
            "doubao-seedance-1-5-pro-251215": "ark-seedance-legacy",
        },
        audioModels: [],
    },
    {
        id: "preset-aliyun-dashscope",
        name: "阿里云百炼",
        baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
        apiKey: "",
        adapterType: "dashscope",
        enabled: false,
        capabilities: ["text", "image", "video"],
        remark: "阿里云百炼 通义千问 / 万相（生图生视频走 DashScope 原生协议，多 Key 轮询）",
        models: [
            "qwen-plus",
            "qwen-max",
            "qwen-turbo",
            "qwen3.7-plus",
            "qwen3.7-max",
            "qwen3.6-flash",
            "qwen-image-2.0-pro",
            "qwen-image-2.0",
            "qwen-image-max",
            "qwen-image-3.0-pro",
            "qwen-image-plus",
            "qwen-image",
            "wan2.7-image",
            "wan2.7-image-pro",
            "wan2.6-t2i",
            "wan2.6-image",
            "z-image-turbo",
            "happyhorse-1.0-t2v",
            "happyhorse-1.0-i2v",
            "happyhorse-1.0-r2v",
            "happyhorse-1.1-t2v",
            "happyhorse-1.1-i2v",
            "happyhorse-1.1-r2v",
            "wan3.0-video",
            "wan3.0-video-prime",
            "wan2.7-t2v",
            "wan2.7-t2v-2026-06-12",
            "wan2.7-t2v-2026-04-25",
            "wan2.7-i2v",
            "wan2.7-i2v-2026-04-25",
            "wan2.7-r2v-2026-06-12",
            "wan2.6-t2v",
            "wan2.6-i2v",
            "wan2.6-i2v-flash",
            "wan2.6-r2v",
            "wan2.6-r2v-flash",
            "wan2.2-kf2v-flash",
            "wan2.7-videoedit",
            "happyhorse-1.0-video-edit",
        ],
        textModels: ["qwen-plus", "qwen-max", "qwen-turbo", "qwen3.7-plus", "qwen3.7-max", "qwen3.6-flash"],
        imageModels: ["qwen-image-3.0-pro", "qwen-image-2.0-pro", "qwen-image-2.0", "qwen-image-max", "qwen-image-plus", "qwen-image", "wan2.7-image-pro", "wan2.7-image", "wan2.6-t2i", "wan2.6-image", "z-image-turbo"],
        videoModels: ["wan3.0-video", "wan3.0-video-prime", "happyhorse-1.0-video-edit", "happyhorse-1.0-t2v", "happyhorse-1.0-i2v", "happyhorse-1.0-r2v", "happyhorse-1.1-t2v", "happyhorse-1.1-i2v", "happyhorse-1.1-r2v", "wan2.7-videoedit", "wan2.7-t2v", "wan2.7-t2v-2026-06-12", "wan2.7-t2v-2026-04-25", "wan2.7-i2v", "wan2.7-i2v-2026-04-25", "wan2.7-r2v-2026-06-12", "wan2.6-t2v", "wan2.6-i2v", "wan2.6-i2v-flash", "wan2.6-r2v", "wan2.6-r2v-flash", "wan2.2-kf2v-flash"],
        audioModels: [],
    },
    {
        id: "preset-aliyun-tokenplan",
        name: "阿里云 Token Plan",
        baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
        apiKey: "",
        adapterType: "dashscope",
        enabled: false,
        capabilities: ["text", "image", "video", "audio"],
        remark: "官方 Token Plan 仅限 Claude Code/Codex 等交互式工具，图像/视频/语音模型需走独立原生 API；图像/视频/音频沿用 DashScope adapter。qwen-audio-3.0-tts-plus 使用官方 SpeechSynthesizer TTS。",
        models: [
            "qwen-image-2.0-pro",
            "qwen-image-2.0",
            "wan2.7-image",
            "wan2.7-image-pro",
            "happyhorse-1.1-t2v",
            "happyhorse-1.0-t2v",
            "happyhorse-1.1-i2v",
            "happyhorse-1.1-r2v",
            "qwen-audio-3.0-tts-plus",
        ],
        textModels: [],
        imageModels: ["qwen-image-2.0-pro", "qwen-image-2.0", "wan2.7-image-pro", "wan2.7-image"],
        videoModels: ["happyhorse-1.1-t2v", "happyhorse-1.0-t2v", "happyhorse-1.1-i2v", "happyhorse-1.1-r2v"],
        audioModels: ["qwen-audio-3.0-tts-plus"],
        endpoints: {
            chat: "/chat/completions",
            images: "/api/v1/services/aigc/multimodal-generation/generation",
            videosCreate: "/api/v1/services/aigc/video-generation/video-synthesis",
            videosPoll: "/api/v1/tasks/{id}",
            audio: "/api/v1/services/audio/tts/SpeechSynthesizer",
        },
    },
    {
        id: "preset-volcengine-ark",
        name: "火山方舟",
        baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
        apiKey: "",
        adapterType: "ark",
        enabled: false,
        capabilities: ["text", "image", "video"],
        remark: "火山方舟 Seedream 生图 / Seedance 生视频（多 Key 轮询）",
        models: [
            "doubao-seedream-5-0-lite-260128",
            "doubao-seedream-5-0-260128",
            "doubao-seedream-4-5-251128",
            "doubao-seedream-4-0-250828",
            "doubao-seedance-2-0-260128",
            "doubao-seedance-2-0-fast-260128",
            "doubao-seedance-2-0-mini-260615",
            "doubao-seedance-1-5-pro-251215",
        ],
        textModels: [],
        imageModels: ["doubao-seedream-5-0-lite-260128", "doubao-seedream-5-0-260128", "doubao-seedream-4-5-251128", "doubao-seedream-4-0-250828"],
        videoModels: ["doubao-seedance-2-0-260128", "doubao-seedance-2-0-fast-260128", "doubao-seedance-2-0-mini-260615", "doubao-seedance-1-5-pro-251215"],
        videoCapabilityProfiles: {
            "doubao-seedance-2-0-260128": "ark-seedance-2",
            "doubao-seedance-2-0-fast-260128": "ark-seedance-2-fast",
            "doubao-seedance-2-0-mini-260615": "ark-seedance-2-mini",
            "doubao-seedance-1-5-pro-251215": "ark-seedance-legacy",
        },
        audioModels: [],
    },
    {
        id: "preset-sensenova",
        name: "商汤日日新",
        baseUrl: "https://token.sensenova.cn/v1",
        apiKey: "",
        adapterType: "sensenova",
        enabled: false,
        capabilities: ["text", "image"],
        remark: "SenseNova 日日新（无视频能力；生图 size 仅接受 2048x2048 等大尺寸，多 Key 轮询）",
        models: ["sensenova-6.7-flash-lite", "deepseek-v4-flash", "glm-5.2", "sensenova-u1-fast"],
        textModels: ["sensenova-6.7-flash-lite", "deepseek-v4-flash", "glm-5.2"],
        imageModels: ["sensenova-u1-fast"],
        videoModels: [],
        audioModels: [],
    },
    {
        id: "preset-agnes-ai",
        name: "Agnes AI",
        baseUrl: "https://apihub.agnes-ai.com/v1",
        apiKey: "",
        adapterType: "agnes",
        enabled: false,
        capabilities: ["text", "image", "video"],
        remark: "Agnes AI 多模态中转（国内网络可能无法直连，多 Key 轮询）",
        models: [
            "agnes-2.5-pro-alpha",
            "agnes-2.5-flash",
            "agnes-2.0-flash",
            "agnes-image-2.1-flash",
            "agnes-image-2.0-flash",
            "agnes-video-v2.0",
        ],
        textModels: ["agnes-2.5-pro-alpha", "agnes-2.5-flash", "agnes-2.0-flash"],
        imageModels: ["agnes-image-2.1-flash", "agnes-image-2.0-flash"],
        videoModels: ["agnes-video-v2.0"],
        audioModels: [],
    },
    {
        id: "preset-civitai-orchestration",
        name: "Civitai Orchestration",
        baseUrl: "https://orchestration.civitai.com/v2/consumer",
        apiKey: "",
        adapterType: "civitai-orchestration",
        enabled: false,
        capabilities: ["image", "video"],
        remark: "Civitai 图片/视频生成目录（成人内容默认关闭，需在中转设置中显式开启；内置列表仅为已验证快照，完整目录以 /v2/services 实时刷新为准；国内网络可能无法直连）",
        models: CIVITAI_PRESET_MODELS,
        textModels: [],
        imageModels: CIVITAI_PRESET_IMAGE_MODELS,
        videoModels: CIVITAI_PRESET_VIDEO_MODELS,
        audioModels: [],
    },
    {
        id: "preset-grok-relay",
        name: "Grok 中转",
        baseUrl: "https://sub.alibb123.ccwu.cc/v1",
        apiKey: "",
        adapterType: "xai-imagine",
        enabled: false,
        capabilities: ["text", "image", "video"],
        remark: "自建 Grok 中转。文本 /chat/completions，Imagine 图 /images/generations，视频 /videos/generations。",
        models: ["grok-4.6", "grok-4.5", "grok-4.3", "grok-imagine-image-quality", "grok-imagine-image", "grok-imagine-image-2.0", "grok-imagine-video", "grok-imagine-video-1.5", "grok-imagine-video-1.5-preview"],
        textModels: ["grok-4.6", "grok-4.5", "grok-4.3"],
        imageModels: ["grok-imagine-image-quality", "grok-imagine-image", "grok-imagine-image-2.0"],
        videoModels: ["grok-imagine-video", "grok-imagine-video-1.5", "grok-imagine-video-1.5-preview"],
        audioModels: [],
        videoCapabilityProfiles: {
            "grok-imagine-video": "xai-imagine-video",
            "grok-imagine-video-1.5": "xai-imagine-video",
            "grok-imagine-video-1.5-preview": "xai-imagine-video",
        },
    },
    {
        id: "preset-fal",
        name: "Fal.ai",
        baseUrl: "https://fal.run",
        apiKey: "",
        adapterType: "fal",
        authScheme: "Key",
        enabled: false,
        capabilities: ["image"],
        remark: "Fal.ai 图片模型。Authorization: Key。模型 ID 自动映射到 fal-ai/ 官方 endpoint。",
        models: ["flux-2-pro", "flux-2-flex", "flux-2-flash", "flux-dev", "flux-schnell", "nano-banana", "nano-banana-pro", "seedream-4.5"],
        textModels: [],
        imageModels: ["flux-2-pro", "flux-2-flex", "flux-2-flash", "flux-dev", "flux-schnell", "nano-banana", "nano-banana-pro", "seedream-4.5"],
        videoModels: [],
        audioModels: [],
    },
    {
        id: "preset-huggingface",
        name: "Hugging Face",
        baseUrl: "https://router.huggingface.co/nscale/v1",
        apiKey: "",
        adapterType: "huggingface",
        enabled: false,
        capabilities: ["image"],
        remark: "HF Inference Providers。生图走 nscale /v1/images/generations，返回 b64_json。",
        models: ["black-forest-labs/FLUX.1-schnell", "black-forest-labs/FLUX.2-dev", "Tongyi-MAI/Z-Image-Turbo"],
        textModels: [],
        imageModels: ["black-forest-labs/FLUX.1-schnell", "black-forest-labs/FLUX.2-dev", "Tongyi-MAI/Z-Image-Turbo"],
        videoModels: [],
        audioModels: [],
    },
    {
        id: "preset-modelscope",
        name: "ModelScope 魔搭（国际站）",
        baseUrl: "https://api-inference.modelscope.ai/v1",
        apiKey: "",
        adapterType: "modelscope",
        enabled: false,
        capabilities: ["image"],
        remark: "国际站 API-Inference。异步生图 /images/generations + 轮询 /tasks。与中国站令牌不通用。",
        models: ["Qwen/Qwen-Image", "Tongyi-MAI/Z-Image-Turbo", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509"],
        textModels: [],
        imageModels: ["Qwen/Qwen-Image", "Tongyi-MAI/Z-Image-Turbo", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509"],
        videoModels: [],
        audioModels: [],
    },
    {
        id: "preset-modelscope-cn",
        name: "ModelScope 魔搭（中国站）",
        baseUrl: "https://api-inference.modelscope.cn/v1",
        apiKey: "",
        adapterType: "modelscope",
        enabled: false,
        capabilities: ["image"],
        remark: "中国站 API-Inference。与国际站令牌不通用，需在中国站单独申请。",
        models: ["Qwen/Qwen-Image", "Tongyi-MAI/Z-Image-Turbo", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509"],
        textModels: [],
        imageModels: ["Qwen/Qwen-Image", "Tongyi-MAI/Z-Image-Turbo", "Qwen/Qwen-Image-Edit", "Qwen/Qwen-Image-Edit-2509"],
        videoModels: [],
        audioModels: [],
    },
    {
        id: "preset-nanogpt",
        name: "NanoGPT",
        baseUrl: "https://nano-gpt.com/v1",
        apiKey: "",
        adapterType: "openai-compat",
        enabled: false,
        capabilities: ["text", "image"],
        remark: "NanoGPT 聚合站。对话 /chat/completions，生图走 OpenAI 兼容 /images/generations（不是文档里的 /api/v1）。",
        models: ["deepseek-chat", "deepseek-r1", "kimi-k2-instruct-fast", "gemini-2.5-pro-preview-06-05", "nano-banana-2", "nano-banana-pro", "gpt-image-2", "gpt-image-1.5", "flux-2-pro", "flux-2-turbo", "seedream-v5.0-lite", "qwen-image-2.0-pro", "z-image-turbo", "hidream"],
        textModels: ["deepseek-chat", "deepseek-r1", "kimi-k2-instruct-fast", "gemini-2.5-pro-preview-06-05"],
        imageModels: ["nano-banana-2", "nano-banana-pro", "gpt-image-2", "gpt-image-1.5", "flux-2-pro", "flux-2-turbo", "seedream-v5.0-lite", "qwen-image-2.0-pro", "z-image-turbo", "hidream"],
        videoModels: [],
        audioModels: [],
    },
];

export function getPresetById(id: string) {
    return PRESET_RELAY_ENDPOINTS.find((p) => p.id === id);
}
