/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CanvasRepairRouteImport } from './routes/canvas-repair'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as EcommerceRouteImport } from './routes/ecommerce'
import { Route as EditRouteImport } from './routes/edit'
import { Route as FramesRouteImport } from './routes/frames'
import { Route as I2vRouteImport } from './routes/i2v'
import { Route as ImageRouteImport } from './routes/image'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StoryRouteImport } from './routes/story'
import { Route as VideoRouteImport } from './routes/video'
import { Route as WebdavProxyRouteImport } from './routes/webdav-proxy'
import { Route as CanvasIndexRouteImport } from './routes/canvas/index'
import { Route as CanvasHomeRouteImport } from './routes/canvas/home'
import { Route as CanvasWorkspaceRouteImport } from './routes/canvas/workspace'
import { Route as ClientApiFetchUrlRouteImport } from './routes/client-api/fetch-url'
import { Route as ClientApiHealthRouteImport } from './routes/client-api/health'
import { Route as ClientApiUploadImageHostRouteImport } from './routes/client-api/upload-image-host'
import { Route as ClientApiUploadWorkMediaRouteImport } from './routes/client-api/upload-work-media'
import { Route as LocalRelayProxySplatRouteImport } from './routes/local-relay-proxy/$'
import { Route as WorksSplatRouteImport } from './routes/works/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRepairRoute = CanvasRepairRouteImport.update({
  id: '/canvas-repair',
  path: '/canvas-repair',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceRoute = EcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => rootRouteImport,
} as any)
const EditRoute = EditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const FramesRoute = FramesRouteImport.update({
  id: '/frames',
  path: '/frames',
  getParentRoute: () => rootRouteImport,
} as any)
const I2vRoute = I2vRouteImport.update({
  id: '/i2v',
  path: '/i2v',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const WebdavProxyRoute = WebdavProxyRouteImport.update({
  id: '/webdav-proxy',
  path: '/webdav-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasIndexRoute = CanvasIndexRouteImport.update({
  id: '/canvas/',
  path: '/canvas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasHomeRoute = CanvasHomeRouteImport.update({
  id: '/canvas/home',
  path: '/canvas/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasWorkspaceRoute = CanvasWorkspaceRouteImport.update({
  id: '/canvas/workspace',
  path: '/canvas/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientApiFetchUrlRoute = ClientApiFetchUrlRouteImport.update({
  id: '/client-api/fetch-url',
  path: '/client-api/fetch-url',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientApiHealthRoute = ClientApiHealthRouteImport.update({
  id: '/client-api/health',
  path: '/client-api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientApiUploadImageHostRoute =
  ClientApiUploadImageHostRouteImport.update({
    id: '/client-api/upload-image-host',
    path: '/client-api/upload-image-host',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientApiUploadWorkMediaRoute =
  ClientApiUploadWorkMediaRouteImport.update({
    id: '/client-api/upload-work-media',
    path: '/client-api/upload-work-media',
    getParentRoute: () => rootRouteImport,
  } as any)
const LocalRelayProxySplatRoute = LocalRelayProxySplatRouteImport.update({
  id: '/local-relay-proxy/$',
  path: '/local-relay-proxy/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WorksSplatRoute = WorksSplatRouteImport.update({
  id: '/works/$',
  path: '/works/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/canvas-repair': typeof CanvasRepairRoute
  '/catalog': typeof CatalogRoute
  '/ecommerce': typeof EcommerceRoute
  '/edit': typeof EditRoute
  '/frames': typeof FramesRoute
  '/i2v': typeof I2vRoute
  '/image': typeof ImageRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/video': typeof VideoRoute
  '/webdav-proxy': typeof WebdavProxyRoute
  '/canvas/home': typeof CanvasHomeRoute
  '/canvas/workspace': typeof CanvasWorkspaceRoute
  '/client-api/fetch-url': typeof ClientApiFetchUrlRoute
  '/client-api/health': typeof ClientApiHealthRoute
  '/client-api/upload-image-host': typeof ClientApiUploadImageHostRoute
  '/client-api/upload-work-media': typeof ClientApiUploadWorkMediaRoute
  '/local-relay-proxy/$': typeof LocalRelayProxySplatRoute
  '/works/$': typeof WorksSplatRoute
  '/canvas/': typeof CanvasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/canvas-repair': typeof CanvasRepairRoute
  '/catalog': typeof CatalogRoute
  '/ecommerce': typeof EcommerceRoute
  '/edit': typeof EditRoute
  '/frames': typeof FramesRoute
  '/i2v': typeof I2vRoute
  '/image': typeof ImageRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/video': typeof VideoRoute
  '/webdav-proxy': typeof WebdavProxyRoute
  '/canvas/home': typeof CanvasHomeRoute
  '/canvas/workspace': typeof CanvasWorkspaceRoute
  '/client-api/fetch-url': typeof ClientApiFetchUrlRoute
  '/client-api/health': typeof ClientApiHealthRoute
  '/client-api/upload-image-host': typeof ClientApiUploadImageHostRoute
  '/client-api/upload-work-media': typeof ClientApiUploadWorkMediaRoute
  '/local-relay-proxy/$': typeof LocalRelayProxySplatRoute
  '/works/$': typeof WorksSplatRoute
  '/canvas': typeof CanvasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/canvas-repair': typeof CanvasRepairRoute
  '/catalog': typeof CatalogRoute
  '/ecommerce': typeof EcommerceRoute
  '/edit': typeof EditRoute
  '/frames': typeof FramesRoute
  '/i2v': typeof I2vRoute
  '/image': typeof ImageRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/settings': typeof SettingsRoute
  '/story': typeof StoryRoute
  '/video': typeof VideoRoute
  '/webdav-proxy': typeof WebdavProxyRoute
  '/canvas/home': typeof CanvasHomeRoute
  '/canvas/workspace': typeof CanvasWorkspaceRoute
  '/client-api/fetch-url': typeof ClientApiFetchUrlRoute
  '/client-api/health': typeof ClientApiHealthRoute
  '/client-api/upload-image-host': typeof ClientApiUploadImageHostRoute
  '/client-api/upload-work-media': typeof ClientApiUploadWorkMediaRoute
  '/local-relay-proxy/$': typeof LocalRelayProxySplatRoute
  '/works/$': typeof WorksSplatRoute
  '/canvas/': typeof CanvasIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/canvas-repair'
    | '/catalog'
    | '/ecommerce'
    | '/edit'
    | '/frames'
    | '/i2v'
    | '/image'
    | '/library'
    | '/login'
    | '/register'
    | '/settings'
    | '/story'
    | '/video'
    | '/webdav-proxy'
    | '/canvas/home'
    | '/canvas/workspace'
    | '/client-api/fetch-url'
    | '/client-api/health'
    | '/client-api/upload-image-host'
    | '/client-api/upload-work-media'
    | '/local-relay-proxy/$'
    | '/works/$'
    | '/canvas/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/canvas-repair'
    | '/catalog'
    | '/ecommerce'
    | '/edit'
    | '/frames'
    | '/i2v'
    | '/image'
    | '/library'
    | '/login'
    | '/register'
    | '/settings'
    | '/story'
    | '/video'
    | '/webdav-proxy'
    | '/canvas/home'
    | '/canvas/workspace'
    | '/client-api/fetch-url'
    | '/client-api/health'
    | '/client-api/upload-image-host'
    | '/client-api/upload-work-media'
    | '/local-relay-proxy/$'
    | '/works/$'
    | '/canvas'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/canvas-repair'
    | '/catalog'
    | '/ecommerce'
    | '/edit'
    | '/frames'
    | '/i2v'
    | '/image'
    | '/library'
    | '/login'
    | '/register'
    | '/settings'
    | '/story'
    | '/video'
    | '/webdav-proxy'
    | '/canvas/home'
    | '/canvas/workspace'
    | '/client-api/fetch-url'
    | '/client-api/health'
    | '/client-api/upload-image-host'
    | '/client-api/upload-work-media'
    | '/local-relay-proxy/$'
    | '/works/$'
    | '/canvas/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CanvasRepairRoute: typeof CanvasRepairRoute
  CatalogRoute: typeof CatalogRoute
  EcommerceRoute: typeof EcommerceRoute
  EditRoute: typeof EditRoute
  FramesRoute: typeof FramesRoute
  I2vRoute: typeof I2vRoute
  ImageRoute: typeof ImageRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SettingsRoute: typeof SettingsRoute
  StoryRoute: typeof StoryRoute
  VideoRoute: typeof VideoRoute
  WebdavProxyRoute: typeof WebdavProxyRoute
  CanvasHomeRoute: typeof CanvasHomeRoute
  CanvasWorkspaceRoute: typeof CanvasWorkspaceRoute
  ClientApiFetchUrlRoute: typeof ClientApiFetchUrlRoute
  ClientApiHealthRoute: typeof ClientApiHealthRoute
  ClientApiUploadImageHostRoute: typeof ClientApiUploadImageHostRoute
  ClientApiUploadWorkMediaRoute: typeof ClientApiUploadWorkMediaRoute
  LocalRelayProxySplatRoute: typeof LocalRelayProxySplatRoute
  WorksSplatRoute: typeof WorksSplatRoute
  CanvasIndexRoute: typeof CanvasIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas-repair': {
      id: '/canvas-repair'
      path: '/canvas-repair'
      fullPath: '/canvas-repair'
      preLoaderRoute: typeof CanvasRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce': {
      id: '/ecommerce'
      path: '/ecommerce'
      fullPath: '/ecommerce'
      preLoaderRoute: typeof EcommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit': {
      id: '/edit'
      path: '/edit'
      fullPath: '/edit'
      preLoaderRoute: typeof EditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frames': {
      id: '/frames'
      path: '/frames'
      fullPath: '/frames'
      preLoaderRoute: typeof FramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/i2v': {
      id: '/i2v'
      path: '/i2v'
      fullPath: '/i2v'
      preLoaderRoute: typeof I2vRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/webdav-proxy': {
      id: '/webdav-proxy'
      path: '/webdav-proxy'
      fullPath: '/webdav-proxy'
      preLoaderRoute: typeof WebdavProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/': {
      id: '/canvas/'
      path: '/canvas'
      fullPath: '/canvas/'
      preLoaderRoute: typeof CanvasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/home': {
      id: '/canvas/home'
      path: '/canvas/home'
      fullPath: '/canvas/home'
      preLoaderRoute: typeof CanvasHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/workspace': {
      id: '/canvas/workspace'
      path: '/canvas/workspace'
      fullPath: '/canvas/workspace'
      preLoaderRoute: typeof CanvasWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-api/fetch-url': {
      id: '/client-api/fetch-url'
      path: '/client-api/fetch-url'
      fullPath: '/client-api/fetch-url'
      preLoaderRoute: typeof ClientApiFetchUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-api/health': {
      id: '/client-api/health'
      path: '/client-api/health'
      fullPath: '/client-api/health'
      preLoaderRoute: typeof ClientApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-api/upload-image-host': {
      id: '/client-api/upload-image-host'
      path: '/client-api/upload-image-host'
      fullPath: '/client-api/upload-image-host'
      preLoaderRoute: typeof ClientApiUploadImageHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-api/upload-work-media': {
      id: '/client-api/upload-work-media'
      path: '/client-api/upload-work-media'
      fullPath: '/client-api/upload-work-media'
      preLoaderRoute: typeof ClientApiUploadWorkMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-relay-proxy/$': {
      id: '/local-relay-proxy/$'
      path: '/local-relay-proxy/$'
      fullPath: '/local-relay-proxy/$'
      preLoaderRoute: typeof LocalRelayProxySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/works/$': {
      id: '/works/$'
      path: '/works/$'
      fullPath: '/works/$'
      preLoaderRoute: typeof WorksSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CanvasRepairRoute: CanvasRepairRoute,
  CatalogRoute: CatalogRoute,
  EcommerceRoute: EcommerceRoute,
  EditRoute: EditRoute,
  FramesRoute: FramesRoute,
  I2vRoute: I2vRoute,
  ImageRoute: ImageRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SettingsRoute: SettingsRoute,
  StoryRoute: StoryRoute,
  VideoRoute: VideoRoute,
  WebdavProxyRoute: WebdavProxyRoute,
  CanvasHomeRoute: CanvasHomeRoute,
  CanvasWorkspaceRoute: CanvasWorkspaceRoute,
  ClientApiFetchUrlRoute: ClientApiFetchUrlRoute,
  ClientApiHealthRoute: ClientApiHealthRoute,
  ClientApiUploadImageHostRoute: ClientApiUploadImageHostRoute,
  ClientApiUploadWorkMediaRoute: ClientApiUploadWorkMediaRoute,
  LocalRelayProxySplatRoute: LocalRelayProxySplatRoute,
  WorksSplatRoute: WorksSplatRoute,
  CanvasIndexRoute: CanvasIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
